### ISSUE TITLE
Unable to tell when a midi has finished

### ISSUE THREAD

**Issue by Emersont1** [sinshu/meltysynth#13]
When a file is not looping, Is there a way to tell when the media has finished playing? I've been looking at the examples, and there appears to be no difference in output in the Render function when the midi has finished playing, is there a way I can check that a midi has finished playing?

**Comment by sinshu** [comment]
Currently, there is not a direct way to tell when the media has finished playing.
But it can be done by comparing the length of the MIDI file to the number of samples written.

I think something like `MidiFileSequencer.EndOfSequence` should be added.

**Comment by sinshu** [comment]
I added `MidiFileSequencer.EndOfSequence`.
Check this flag to see if the sequencer is still playing.
A new nuget package with this update is available.
