### ISSUE TITLE
Sample in sound font with start loop = 0 and end loop = 0

### ISSUE THREAD

**Issue by postacik** [sinshu/meltysynth#14]
This is a great library! Thanks for your excellent work.

 I have a sound font file in which start loop and end loop values for all samples is zero. 

[p1.zip](https://github.com/sinshu/meltysynth/files/8598573/p1.zip)

This file raises an exception in CheckSamples() and CheckRegions() functions in SoundFont.cs.

I don't know if having both values as zero is permitted or not but another sound font library I use does not complain about this issue.

I fixed this problem by changing the condition from < to <= in the following parts of the code:

```
                if (!(0 <= sample.EndLoop && sample.EndLoop <= sampleCount))
                {
                    throw new InvalidDataException($"The loop end position of the sample '{sample.Name}' is out of range.");
                }

                if (!(0 <= region.SampleEndLoop && region.SampleEndLoop <= sampleCount))
                {
                    throw new InvalidDataException($"The loop end position of the sample '{region.Sample.Name}' in the instrument '{instrument.Name}' is out of range.");
                }

```
Can you also update it if having both values as zero does not effect the synthesize process?

**Comment by sinshu** [comment]
If the sample is set to non-loop mode, the end loop value will never be referenced, so it's OK to set the end loop value to zero. Actually, this is not allowed in the SoundFont specs, but some SoundFonts use this trick.

It seems that a strict check in this area would require complex code, so it would be better to just relax the conditions as you have pointed out.

Please check this commit: https://github.com/sinshu/meltysynth/commit/549b8339647db9f2697ce35615e7d93e2b4aa39b

**Comment by postacik** [comment]
Thanks :)
