### ISSUE TITLE
Possible typo?

### ISSUE THREAD

**Issue by MistressRemilia** [sinshu/meltysynth#15]
I noticed that in Synthesizer.ProcessMidiMessage(), the controller messages for the modulation are both set to call SetModulationCoase().  But on line 190, should that be SetModulationFine() instead of SetModulationCoarse()?

https://github.com/sinshu/meltysynth/blob/549b8339647db9f2697ce35615e7d93e2b4aa39b/MeltySynth/src/Synthesizer.cs#L185-L191

**Comment by sinshu** [comment]
Thank you for reporting the issue.
This is indeed my typo.


Fixed in this commit: https://github.com/sinshu/meltysynth/commit/8109c0e1b5c6f384e9719f21eda055c763a7f606

**Comment by sinshu** [comment]
A new nuget package with this update is available, so this issue can be closed.
