### ISSUE TITLE
Parametric chorus and reverb

### ISSUE THREAD

**Issue by postacik** [sinshu/meltysynth#16]
Chorus and reverb effects are applied with predefined parameter values.

Can it be possible to set the parameters of these effects in SynthesizerSettings?

**Comment by sinshu** [comment]
Thank you for the suggestion, but I want to keep the effect parameters hidden for API simplicity.

If you need to change the effect parameters, I recommend that you copy the source code of this library to your project and edit the code to make the parameters accessible.

**Comment by postacik** [comment]
Fair enough, thanks...
