### ISSUE TITLE
Big sound font files

### ISSUE THREAD

**Issue by postacik** [sinshu/meltysynth#18]
I have some sound font files which are hundreds of megabytes or even a gigabyte in size.

When a sound font is loaded, all the data in it is read into memory.

This is generally not a problem on a PC, but on a mobile phone such sound font files create a memory issue. (I am also using the dart version of this library ([DartMeltySoundFont](https://github.com/chipweinberger/DartMeltySoundFont)) in an Android application)

Assuming that the external storage is fast enough for lazy loading and processing, is it possible to load samples whenever they are needed into a predefined maximum memory space?

**Comment by postacik** [comment]
Can you give me a head start telling how you would do it if  you were to do it?

**Comment by sinshu** [comment]
I would do the following things:

Originally a `SampleHeader` has the start and end index of the big `short[]`. Instead, each `SampleHeader` will have a reference to a cached waveform like `short[] cache`, which is initially null.

When a new note is requested, check if the corresponding `SampleHeader`'s `short[] cache` is null or not. If null, read the corresponding waveform from the sf2 and save it to `cache`. `cache` is then passed to the oscillator, and the rest is the same as before.

Deleting old cache when reaching the memory limit might be complex. I believe a cache which is not recently used should be deleted first, but I'm not sure how to well prioritize them in real application. Some trial and error might be necessary here.
