### ISSUE TITLE
Add InstrumentChange constant

### ISSUE THREAD

**Issue by MatheusMoura17** [sinshu/meltysynth#26]
In alternative to #25, we can add single constant `InstrumentChange` inside Synthesizer?

Sample:

Before
```cs
// Change the instrument to electric guitar (#30).
synthesizer.ProcessMidiMessage(0, 0xC0, 30, 0);
```

After
```cs
// Change the instrument to electric guitar (#30).
synthesizer.ProcessMidiMessage(0, Synthesizer.InstrumentChange, 30, 0);
```

**Comment by sinshu** [comment]
There are a number of commands defined in the General MIDI specifications.
Is there a particular reason to add a constant only for instrument change?

**Comment by MatheusMoura17** [comment]
`0xC0` its a unique code i'm using in HGS-Tone:

```cs
    public void SetInstrument(MidiInstrumentCode code)
    {
      SetInstrument((int)code);
    }

    public void SetInstrument(int id)
    {
      _synthesizer.ProcessMidiMessage(0, 0xC0, id, 0);
    }
```

I was thinking of creating a constant `InstrumentChange` in my code, but I think having this constant in `MeltySynth` could help other people. My library is too simple, I don't think I will manage MIDI codes.

**Comment by sinshu** [comment]
Here is my opinion:

I believe that this library should provide only what users cannot easily achieve. Since adding a constant for convenience is not hard for users, that should not be in the library. This is mainly to keep the API simple.

**Comment by MatheusMoura17** [comment]
Hey, sorry for delay, i agree with you, i'll keep the constants in my code base.

Thank you! :D
