### ISSUE TITLE
Question: How to select an instrument to play the notes with?

### ISSUE THREAD

**Issue by HubKing** [sinshu/meltysynth#3]
I tried the chord example, and it sounded like a piano. What if I want to play some other instrument in the sound font? How to change the instrument? I even looked at the source code for `NoteOn` but I could not figure it out. Is it hardcoded to be a piano or the first instrument?

```
// Play some notes (middle C, E, G).
synthesizer.NoteOn(0, 60, 100);
synthesizer.NoteOn(0, 64, 100);
synthesizer.NoteOn(0, 67, 100);

```

**Comment by sinshu** [comment]
To change the instrument, send the [program change](https://en.wikipedia.org/wiki/General_MIDI#Program_change_events) command to the synthesizer.

This is an example to play notes with electric guitar sound:
```cs
// Change the instrument to electric guitar.
synthesizer.ProcessMidiMessage(0, 0xC0, 30, 0);

// Play some notes (middle C, E, G).
synthesizer.NoteOn(0, 60, 100);
synthesizer.NoteOn(0, 64, 100);
synthesizer.NoteOn(0, 67, 100);
```

The value `0xC0` indicates the program change command, which makes the synthesizer switch the instrument to the desired one.
If the SoundFont is general MIDI compatible, the instrument number `30` corresponds to electric guitar.
