### ISSUE TITLE
Possible .dls soundfont Support?

### ISSUE THREAD

**Issue by mysterypaint** [sinshu/meltysynth#30]
Hello,

First of all, thank you for making this library! It's been such a huge help in my project.

I was wondering, is there room for adding .dls support? I used AWave Studio to convert .dls -> .sf2, but the results are not 100% accurate: I suspect that the volume envelopes (ADSR) and tuning/pitch output might be slightly different from the source material.

You can find my project here, for reference: https://github.com/mysterypaint/OpenLaMulana

Thank you for your time!

- mysterypaint

**Comment by sinshu** [comment]
To keep the code simple, DLS will not be supported.

Actually, I believe "slightly different" is unavoidable in this area. There are degrees of freedom in implementation, resulting in different sounds even when implementations are based on the same specifications.

Anyway, your project looks cool 😄
