### ISSUE TITLE
Disable reverb?

### ISSUE THREAD

**Issue by guighub** [sinshu/meltysynth#37]
Hi, I'm using this to batch convert sequenced Nintendo DS music, and I need it to be as accurate as possible. The DS doesn't really have many effects, so I'd like to minimize the reverb and other effects that are applied when rendering. Is there any way to disable reverb and other effects?

**Comment by sinshu** [comment]
Try running the following code:

```cs
var settings = new SynthesizerSettings(44100);
settings.EnableReverbAndChorus = false;
var synthesizer = new Synthesizer("your_soundfont.sf2", settings);
```

**Comment by guighub** [comment]
Perfect, thanks!
