### ISSUE TITLE
Generate specific sample range and change position

### ISSUE THREAD

**Issue by achimmihca** [sinshu/meltysynth#38]
I have a Unity game and want to play user provided MIDI files on the fly.

Therefor, I want to synthesize samples when needed, not all at once.
For example, my code may look similar to this:

```
private void CreateAudioClip()
{
    audioSource.clip = AudioClip.Create("MIDI {fileName}", audioClipLengthInSamples, midiSynthesizerChannelCount, audioClipSampleRate, true, OnAudioClipRead, OnAudioClipSetPosition);
}

private void OnAudioClipRead(float[] data)
{
    // This method is called when Unity plays the audio.
    // It asks for samples from `audioClip.timeSamples` to `audioClip.timeSamples + data.Length`
    FillOutputBuffer(data, midiSynthesizerChannelCount);
}

private void OnAudioClipSetPosition(int positionInSamples)
{
    // This method is called when Unity changes the playback position.
    // It sets audioClip.timeSamples
    sequencer.SeekSampleTime(positionInSamples);
}
```

I found the Render method of MeltySynth to be good.
However, I did not find a way to change the playback position. Is this missing or am I looking in the wrong place?

So far, I use [this other lib](https://github.com/TriggerCoder/CSharpSynthForUnity2.0) to play MIDI in Unity, but it has issues with some MIDI files.

Thanks for the help!

**Comment by sinshu** [comment]
MIDI files inherently do not work well with operations like seeking, and it's challenging to implement a seek function that can meet the demands of many users. Therefore, the MidiFileSequencer in MeltySynth does not provide a seek method. If you need to seek, please consider implementing your own sequencer.

**Comment by achimmihca** [comment]
Thanks for the info. In this case, I will close this issue.
