### ISSUE TITLE
Question: How to play notes with timing?

### ISSUE THREAD

**Issue by HubKing** [sinshu/meltysynth#4]
The example plays three note at the same time, from start to end, sort of like this.

![image](https://user-images.githubusercontent.com/83916931/117579745-3a064200-b12f-11eb-801d-17e3111eddd7.png)

But what if I want the start time not to be at the beginning and the end time not to be the end?  Something like the followings?

![image](https://user-images.githubusercontent.com/83916931/117579804-8782af00-b12f-11eb-82b4-44bdd9b22bfd.png)

The `NoteOn` method do not seem to have any timing parameter, and the other method is `NoteOff`, but I don't get how to use these to play notes with timing.

**Comment by sinshu** [comment]
You can do that by rendering the sound as a sequence of short blocks.

This is an example code to play the notes at different timings:
```cs
// Create the synthesizer.
var sampleRate = 44100;
var synthesizer = new Synthesizer("TimGM6mb.sf2", sampleRate);

// The length of a block is 0.1 sec.
var blockSize = sampleRate / 10;

// The entire output is 3 sec.
var blockCount = 30;

// Define the melody.
// A single row indicates the start timing, end timing, and pitch.
var data = new int[][]
{
    new int[] {  5, 10, 60 },
    new int[] { 10, 15, 64 },
    new int[] { 15, 25, 67 }
};

// The output buffer.
var left = new float[blockSize * blockCount];
var right = new float[blockSize * blockCount];

for (var t = 0; t < blockCount; t++)
{
    // Process the melody.
    foreach (var row in data)
    {
        if (t == row[0]) synthesizer.NoteOn(0, row[2], 100);
        if (t == row[1]) synthesizer.NoteOff(0, row[2]);
    }

    // Render the block.
    var blockLeft = left.AsSpan(blockSize * t, blockSize);
    var blockRight = right.AsSpan(blockSize * t, blockSize);
    synthesizer.Render(blockLeft, blockRight);
}
```

This API might look odd, but this is necessary for realtime applications in which notes to play in the future are unknown.

**Comment by sinshu** [comment]
The easiest way to play the sound is to export it to a WAV file, so that you can hear the sound on an ordinary audio player.

You can do this easily with NAudio. Check the sample code below.
https://github.com/sinshu/meltysynth/blob/5ba5f142bb90a397f5dc509b3b552eff7589ba99/Workspace/RenderingTest.cs#L50
