### ISSUE TITLE
[Discussion] add a synth.selectPreset function? 

### ISSUE THREAD

**Issue by chipweinberger** [sinshu/meltysynth#40]
In my README, I have these rather wordy docs.

```
You might want to select the patchNumber & bankNumber
of the instrument you want to play, if it's not 0.

Look through synth.soundFont.presets[X].patchNumber & bankNumber
for all valid instrument choices.

Example for setting patchNumer:

  int patchNumber = synth.soundFont.presets[0].patchNumber 
  synth.processMidiMessage(
    channel:0, 
    command:0xC0, // 0xC0 = program changes
    data1:patchNumber, 
    data2:0
  );

Example for setting bankNumber:

  int bankNumber = synth.soundFont.presets[0].bankNumber 
  synth.processMidiMessage(
    channel:0, 
    command:0xB0, // 0xB0 = control change
    data1:0x00,   // 0x00 = bank select
    data2:bankNumber,
  );
```

So simplify things, perhaps we could add a `synth. selectPreset(int channel, int preset)` function?

```
void selectPreset(int channel, int preset)
{
    if (preset >= synth.soundFont.presets.length) {
        throw InvalidArgument('selectInstrumentPreset: invalid preset $preset >= ${synth.soundFont.presets.length}');
    }

    this.processMidiMessage(
        channel: channel, 
        command: 0xC0, // program change
        data1: this.soundFont.presets[preset].patchNumber, 
        data2: 0
    );

    this.processMidiMessage(
        channel: channel, 
        command: 0xB0, // control change
        data1: 0x00,   // bank select
        data2: this.soundFont.presets[preset].bankNumber,
    );
}
```

Curious your thoughts @sinshu

**Comment by chipweinberger** [comment]
this way my example code is simple:

// Necessary Imports
import 'package:dart_melty_soundfont/dart_melty_soundfont.dart';
import 'package:flutter/services.dart' show rootBundle;

// Create the synthesizer.
ByteData bytes = await rootBundle.load('assets/akai_steinway.sf2');

Synthesizer synth = Synthesizer.loadByteData(bytes, 
    SynthesizerSettings(
        sampleRate: 44100, 
        blockSize: 64, 
        maximumPolyphony: 64, 
        enableReverbAndChorus: true,
    ));

// selects the first available instrument
synth.selectInstrument(channel: 0, index: 0);

// Turn on some notes
synth.noteOn(channel: 0, key: 72, velocity: 120);
synth.noteOn(channel: 0, key: 76, velocity: 120);
synth.noteOn(channel: 0, key: 79, velocity: 120);
synth.noteOn(channel: 0, key: 82, velocity: 120);


// Render the waveform (3 seconds)
ArrayInt16 buf16 = ArrayInt16.zeros(numShorts: 44100 * 3);

synth.renderMonoInt16(buf16);

**Comment by sinshu** [comment]
I was considering adding several useful methods to `Synthesizer`. For instance, a method like the one below that simplifies program changes:

```cs
public static void ChangeProgram(this Synthesizer synthesizer, int channel, int value)
{
    synthesizer.ProcessMidiMessage(channel, 0xC0, value, 0);
}
```

However, I pondered 🤔
Would it be better for `value` to be `int`, or should it represent the GM sound set as an enum, or should it have overloads for both? Moreover, if there's `ChangeProgram`, it seems logical to also have methods like `ChangeBank`, `SetExpression`, `SetPitchBend`, and so on. Should the argument for `SetExpression` range from 1-127 or would 0.0-1.0 be more intuitive? After much deliberation on such matters, I concluded that users should create such utility methods according to their preferences. Hence, I decided not to provide them.

By the way, in dart_melty_soundfont's simple chord sample, does the mention of the preset serve to avoid silence when the SoundFont doesn't have a preset assigned to #0? If so, you might want to implement a fallback mechanism to a default preset when a preset is not found. #17 and #19 might be helpful references.

**Comment by chipweinberger** [comment]
I pushed e17e5b2fd0f32ef2a1f7803b34e0b4300ef11ef0

**Comment by sinshu** [comment]
> https://github.com/sinshu/meltysynth/commit/d1f8ebe8a86b877831de47e7e3052fc7e5b11edf is an interesting change. So if a complicated midi file with many instruments uses an instrument that is not available in the soundfont, you will get the default preset instead of silence?

Yes, every instrument might turn into a piano or something 😅

To the best of my knowledge, the behavior when a preset is not found is not explicitly stated in either the SoundFont or MIDI specification, so I think it’s ultimately up to the author to decide based on their preferences. Personally, considering the user experience, I thought it was a good decision to make sure that sound is produced as soon as `NoteOn` is executed 🤔

**Comment by chipweinberger** [comment]
yes that makes sense. thanks for your help :)
