### ISSUE TITLE
Virtual Keyboard example

### ISSUE THREAD

**Issue by Dunnymeister** [sinshu/meltysynth#42]
I was wondering if you have any example code demonstrating realtime synthesis using MeltySynth, something along the lines of the [Virtual Keyboard example](https://www.youtube.com/watch?v=a8vuIq4JKhs) in the readme?

**Comment by sinshu** [comment]
The code for the virtual keyboard example is available here:
https://github.com/sinshu/VirtualKeyboard

**Comment by Dunnymeister** [comment]
Thank you very much!
