### ISSUE TITLE
I cant figure out how to use this

### ISSUE THREAD

**Issue by ZSolar1** [sinshu/meltysynth#44]
so im making a framework and i added audio stream implimentation to it a while ago. I found this thing and decided to try it out but for some reason nothing played. Im using your Raylib_cs example, and it works fine but as soon as i try to use it with my library it just doesnt play any sound. i used the same soundfont and midi with your example and it works fine, but mine just doesnt work. this is the details im pretty sure you will need:

Where I set everything up and play the midi:
```cs
short[] buffer;
Synthesizer synthesizer = new Synthesizer("assets/soundfonts/Arachno SoundFont - Version 1.0.sf2", LnG.game.window.sampleRate);
MidiFileSequencer sequencer;
MidiFile midiFile = new MidiFile("assets/songs/Super Mario 64 - Koji Kondo - Bowser Confrontation (Jeff Daily).mid");
override public void Start()
{
    buffer = new short[2 * LnG.game.window.bufferSize];
    sequencer = new MidiFileSequencer(synthesizer);
    sequencer.Play(midiFile, true);
    base.Start();
}
```
Where I render from the sequencer:
```cs
public override void UpdateAudio()
{
    sequencer.RenderInterleavedInt16(buffer);
    base.UpdateAudio();
}
```
Where I call UpdateAudio:
```cs
if (IsAudioStreamProcessed(stream))
{
    LnG.curState.UpdateAudio();
    fixed (short* p = buffer) //used from the Raylib_cs example
    {
        UpdateAudioStream(stream, p, bufferSize);
    }
}
```
Remember that I adapted all of this code from the Raylib_cs example and it just doesnt work.

**Comment by sinshu** [comment]
It's hard to figure out the cause from these code fragments.
Could you provide a minimal reproducible example?

**Comment by ZSolar1** [comment]
i can try, give me a moment.

**Comment by ZSolar1** [comment]
ok i didnt realize how hard it was wtf

**Comment by ZSolar1** [comment]
ok thats it im doing this tmmr or smth its way too difficult to make a portable version of smth that uses an unreleased library
