### ISSUE TITLE
Weird "fade" artifacts - maximum polyphony?

### ISSUE THREAD

**Issue by chipweinberger** [sinshu/meltysynth#47]
https://github.com/sinshu/meltysynth/assets/1863934/187e63cd-7b65-4b17-91bf-7cf15c8f91b9

Hey @sinshu , hello again :)

At 00:11 & 00:24 in the video, you can hear weird artifacts.I think it is due to maximum polyphony. But it still sounds not as expected.

I am playing the same note many times, and the first notes should note be loud anymore. Why is the artifact so large?

**Comment by sinshu** [comment]
Hi 😊

Let me confirm a few things.
* Is this the Dart port?
* Is the SF2 file `TimGM6mb.sf2`?
* What's the maximum polyphony value?

**Comment by chipweinberger** [comment]
Yes. Dart port.

soundfont: akai_steinway.sf2 (https://musical-artifacts.com/artifacts/1876)

maximumPolyphony: 192

**Comment by chipweinberger** [comment]
midi file

[jamcorder-0.mid.txt](https://github.com/user-attachments/files/15874367/jamcorder-0.mid.txt)

**Comment by chipweinberger** [comment]
Thanks for your help @sinshu :)

**Comment by chipweinberger** [comment]
I counted the notes, and it is only about ~50 notes before artifact. So maybe not maximum polyphony.

But I noticed it happens when:
1. sustain pedal is used for long time
2. lots of repeated notes

**Comment by sinshu** [comment]
I haven't pinpointed the cause yet, but I remember dealing with a similar issue in the past.
https://github.com/sinshu/meltysynth/issues/20

It seems that the commit for the C# version hasn't been brought into the Dart version.
https://github.com/sinshu/meltysynth/commit/a8fcf2fc86b73da114b8acf106650ca047afccf3

It might help to port this commit to Dart. Could you please give it a try?

**Comment by chipweinberger** [comment]
yes this sounds like the exact same issue!

I will port it!!

**Comment by chipweinberger** [comment]
what should I do it "low" is null? for `if (voice.voiceLength() > low.voiceLength()) {`



<img width="399" alt="Screenshot 2024-06-17 at 10 19 26 AM" src="https://github.com/sinshu/meltysynth/assets/1863934/d4c0946b-13d3-43e0-9ecc-9d3bdc9d4eec">

**Comment by chipweinberger** [comment]
yes. this changed fixed it!

**Comment by sinshu** [comment]
@chipweinberger
Glad to hear it got resolved 😁

Regarding the issue where `low` might become `null`:

* `low` will not be `null` if `priority < lowestPriority` occurs even once.
* The initial value of `lowestPriority` is `maxFinite`.
* Therefore, for `low` to remain `null` while entering the path where `priority == lowestPriority`, `voice.priority()` must be `maxFinite`.
* However, `voice.priority()` will never return such a large value.

Thus, `low` will never be `null`. In fact, there has never been a null pointer issue in this code path.
