### ISSUE TITLE
Modulator support

### ISSUE THREAD

**Issue by spessasus** [sinshu/meltysynth#48]
Hi,
I've noticed that MeltySynth doesn't support modulators and I haven't seen an issue mentioning them so I'm opening this one.

Modulators are an integral part of the soundfont standard. They allow precise control of the parameters which allows the soundfont to define the way it responds to midi controllers. 
For example I could add support for the brightness controller (74) by mapping it to the initialFilterFC. But currently that doesn't work in MeltySynth.

**Comment by sinshu** [comment]
Thanks for the suggestion, but I do not intend to support modulators for the following reasons 😖
* Modulators are complex, and implementing them is difficult.
* Many SoundFonts do not use modulators, so the benefit is small compared to the difficulty of implementation.

**Comment by spessasus** [comment]
Thanks for the quick response l, @sinshu.

Modulators aren't as difficult as you might think. I've implemented them in my own synthesizer and they are essentially lookup tables.
Here's how I did it:
Create lookup tables that have values from 0 to 1 or -1 to 1 for all curve types, both directions and both polarities.
Each array has 127 elements (midi Controllers have values from 0 to 127)
Like this:
```csharp
modulatorCurves[curveType][polarity][direction] = (127 long table for the controller value corresponding to the curve value of the controller)
```
Then when you compute the modulator, you simply do:
```csharp
int controllerValue = midiControllerValues[modulator.sourceEnum]; // or if modulator doesn't use cc, get the value from the pitch, etc.
int secondaryControllerValue = // same here except for the second source
float sourceValue = modulatorCurves[modulator.souceCurveType][modulator.sourcePolarity][modulator.sourceDirection][controllerValue];
float secondarySourceValue= // same as above except for the second source
float value = modulator.amount * sourceValue * secondarySourceValue;
if(modulator.transformType == transformTypes.absolute)
   value = Math.abs(value);

voice.generators[modulator.destination] += value
```
You can see my implementation [here](https://github.com/spessasus/SpessaSynth/blob/a4e98f5755a17738bfa6e66daabf0aa3a53e84ab/src/spessasynth_lib/synthetizer/worklet_system/worklet_utilities/worklet_modulator.js#L18) and [here](https://github.com/spessasus/SpessaSynth/blob/a4e98f5755a17738bfa6e66daabf0aa3a53e84ab/src/spessasynth_lib/synthetizer/worklet_system/worklet_utilities/modulator_curves.js#L9)

**Comment by spessasus** [comment]
Also modulators are widely used in some popular soundfonts:
Note: these numbers come from polyphone (when you open the soundfont, stats show at the bottom).
- FluidR3_GM.sf2 (probably the most popular free soundfont) uses exactly **746** instrument modulators.
- GeneralUserGS.sf2 (another popular free soundfont) has **2445** instrument modulators.
- Chorium Rev. A (yet another popular free soundfont) uses **2787** instrument modulators.
- SGM soundfont (famous from being used in undertale) uses **1873** instrument modulators.
- Microsoft Wavetable Synth soundfont uses **4601** instrument modulators!
- LiveHQ Natural Soundfont (a very high quality soundfont i use) uses **1419** instrument modulators.

That's why I think that modulators should be supported by MeltySynth as it's the definitive soundfont synth for .NET.

**Comment by sinshu** [comment]
I took a look at your implementation, and the Modulator still seems complex to me. It would be difficult for me to implement and test this feature. Anyway, thank you for the suggestion ☺️
