### ISSUE TITLE
[QUESTION] Set drums on different channels?

### ISSUE THREAD

**Issue by spessasus** [sinshu/meltysynth#50]
How can i make other channels drum channels? I couldn't find it in the documentation.
For example, i want channels 9, 10 and 11 to all be drums. How can I do that?

Example MIDI that uses 3 drum channels (play it through Microsoft GS Wavetable Synth or SpessaSynth):
[multi_drum_midi.zip](https://github.com/user-attachments/files/15987452/mulit_drum_midi.zip)

**Comment by sinshu** [comment]
This library assumes General MIDI Level 1, so it does not have the ability to assign drums to channels other than channel 10.
