### ISSUE TITLE
Soundfont3 support

### ISSUE THREAD

**Issue by spessasus** [sinshu/meltysynth#51]
The SoundFont 3 format (SF3) is an unofficial extension of the SoundFont 2 format (SF2). It was originally created by Werner Schweer for MuseScore with the aim of reducing the file size of their bundled Soundfont(s) by enabling support for Ogg Vorbis compressed samples.

Support for SF3 has since been incorporat
ed into many other SoundFont software packages, for example Polyphone, Swami, Qsynth, FluidSynth, and other software synthesizers. But not meltysynth.

Spec:
https://github.com/FluidSynth/fluidsynth/wiki/SoundFont3Format
As you can see, the code pretty much requires minimal changes. Only the shdr index fields and the sampleType bit checking
Maybe add a vorbis library as an optional dependency? if not provided, synth would throw an error if sf3 is detected.

An example SF3 Soundfont for you to test on: [SGM.zip](https://github.com/user-attachments/files/16389676/SGM.zip)

_Also the other issues I've created should've been closed as "Not planned" rather than "Completed" because they are, well, not planned to be added._

**Comment by sinshu** [comment]
Thanks for the suggestion, but SF3 support is not planned.

**Comment by spessasus** [comment]
That's a shame...
