### ISSUE TITLE
[BUG] Modulation Depth RPN does not work

### ISSUE THREAD

**Issue by spessasus** [sinshu/meltysynth#52]
## The issue
MeltySynth does not read modulation depth messages.

## Specification
[This document, section 3.4.4](http://www.shclemen.com/download/GM2.pdf#page=17)

## Test MIDI file
[test.zip](https://github.com/user-attachments/files/16323312/test-rpn-00-05-modulation-depth-range.zip)

## Expected behavior
The modulation deptj should audibly change. This is a part of the GM standard so it should be implemented.

**Comment by sinshu** [comment]
This library assumes General MIDI Level 1, so mod depth will not be supported.

Also, I do not intend to implement every single feature described in the SoundFont and MIDI specifications for this hobby project. Please do not open similar issues any more.

**Comment by spessasus** [comment]
Alright, understood. Sorry for bombarding you with issues, I won't open any more related to midi or sf spec.
