### ISSUE TITLE
ideas how to deal with clipping?

### ISSUE THREAD

**Issue by chipweinberger** [sinshu/meltysynth#54]
Hey Sinshu, 

I get really bad clipping articfacts. 100% volume is unusable. even 75% is bad. The best is around 40%.

https://github.com/user-attachments/assets/3b68f2fe-2da5-48da-b4c2-27e3d656c7ee

Any ideas how to improve this? Suggested algorithms?

**Comment by sinshu** [comment]
Does your program take any measures when the amplitude exceeds the maximum value? For example, when MeltySynth renders waveforms in int16 format, samples that exceed the maximum value are replaced with -32768 or 32767.

https://github.com/sinshu/meltysynth/blob/465b65047534d5f85f92c8ab271058a163fd13a0/MeltySynth/src/AudioRendererEx.cs#L207

If you are already taking such measures but still find the sound quality during clipping unsatisfactory, it might be necessary to introduce signal processing like a limiter or compressor. However, since I don’t have much experience implementing such algorithms, it’s difficult for me to give good advice...

**Comment by chipweinberger** [comment]
No, I don't take any measures. Just use the default settings with my soundfont.

Yes a compressor is what I expected I need to make. Maybe I'll make one and share it with you.

**Comment by chipweinberger** [comment]
Though, I actually never change the volume. I always send the same volume to the API.

Apple handles the volume.

So maybe I'll need to look at apple APIs

**Comment by chipweinberger** [comment]
actually, because I use this PCM to generate videos, it is better to compress the PCM on my side. 

This is what ChatGPT-o1-preview came up with 

```
import 'dart:math';

class Compressor {
  final double threshold; // Threshold in dB
  final double ratio; // Compression ratio
  final double attackTime; // Attack time in seconds
  final double releaseTime; // Release time in seconds
  final double makeupGain; // Makeup gain in dB

  double _currentGainReduction_dB; // Current gain reduction in dB
  double _attackCoeff; // Attack coefficient
  double _releaseCoeff; // Release coefficient

  Compressor({
    required this.threshold,
    required this.ratio,
    required this.attackTime,
    required this.releaseTime,
    required this.makeupGain,
  })  : _currentGainReduction_dB = 0.0,
        _attackCoeff = 0.0,
        _releaseCoeff = 0.0;

  factory Compressor.create({
    required int sampleRate,
    required double threshold,
    required double ratio,
    required double attackTime,
    required double releaseTime,
    required double makeupGain,
  }) {
    // Ensure attack and release times are greater than zero
    assert(attackTime > 0.0);
    assert(releaseTime > 0.0);

    // Calculate attack and release coefficients
    double attackCoeff = exp(-log(9) / (sampleRate * attackTime));
    double releaseCoeff = exp(-log(9) / (sampleRate * releaseTime));

    return Compressor(
      threshold: threshold,
      ratio: ratio,
      attackTime: attackTime,
      releaseTime: releaseTime,
      makeupGain: makeupGain,
    )
      .._attackCoeff = attackCoeff
      .._releaseCoeff = releaseCoeff;
  }

  void process({
    required List<double> inputLeft,
    required List<double> inputRight,
    required List<double> outputLeft,
    required List<double> outputRight,
  }) {
    assert(inputLeft.length == inputRight.length);
    assert(outputLeft.length == outputRight.length);
    assert(inputLeft.length == outputLeft.length);

    for (int i = 0; i < inputLeft.length; i++) {
      // Calculate the absolute values of the input samples
      double absInputL = inputLeft[i].abs();
      double absInputR = inputRight[i].abs();

      // Use the maximum of left and right channels for level detection
      double absInput = max(absInputL, absInputR);

      // Avoid taking log of zero
      if (absInput < 1e-10) {
        absInput = 1e-10;
      }

      // Convert input level to dB
      double inputLevel_dB = 20.0 * log10(absInput);

      // Calculate desired gain reduction
      double desiredGainReduction_dB = 0.0;
      if (inputLevel_dB > threshold) {
        desiredGainReduction_dB =
            (threshold - inputLevel_dB) * (1.0 - (1.0 / ratio));
      }

      // Select attack or release coefficient based on whether gain reduction is increasing or decreasing
      double coeff;
      if (desiredGainReduction_dB < _currentGainReduction_dB) {
        // Gain reduction increasing (signal exceeds threshold), use attack
        coeff = _attackCoeff;
      } else {
        // Gain reduction decreasing, use release
        coeff = _releaseCoeff;
      }

      // Smooth gain reduction using exponential smoothing
      _currentGainReduction_dB = coeff * _currentGainReduction_dB +
          (1.0 - coeff) * desiredGainReduction_dB;

      // Calculate total gain including makeup gain
      double totalGain_dB = _currentGainReduction_dB + makeupGain;
      double totalGain = pow(10.0, totalGain_dB / 20.0);

      // Apply gain to input samples
      outputLeft[i] = inputLeft[i] * totalGain;
      outputRight[i] = inputRight[i] * totalGain;
    }
  }

  // Optional: Reset the compressor's gain reduction to zero
  void reset() {
    _currentGainReduction_dB = 0.0;
  }
}
```

**Comment by chipweinberger** [comment]
I'm testing it, and the code seems to work. amazing. I have to tune the parameters still.

**Comment by chipweinberger** [comment]
seems hard to get rid of the clipping with acceptable results. not having much luck.

```
    this.compressorThreshold = -30.0,
    this.compressorRatio = 12.0,
    this.compressorAttackTime = 0.0001,
    this.compressorReleaseTime = 0.05,
    this.compressorMakeupGain = -2.0,
```

**Comment by sinshu** [comment]
Is it possible that the issue is hardware-related? I think smartphone speakers are not really designed for producing loud sounds in the first place 🤔

**Comment by chipweinberger** [comment]
could be

**Comment by chipweinberger** [comment]
yes, tried an RMS compressor, Optical compressor, and whatever the default compressor ChatGPT came up with was.

none of them solved the clipping. Barely even made an improvement.

**Comment by chipweinberger** [comment]
> Is it possible that the issue is hardware-related? I think smartphone speakers are not really designed for producing loud sounds in the first place 🤔

Yes, on my Mac is sounds fine. Just the phone. I think it's a lost cause. Will close!

**Comment by chipweinberger** [comment]
actually, I just had an idea.

Instead of trying to compress the output signal. It might be better to compress during _generation_.

for example, if there are 10 loud noteOn notes, we will reduce the volume of each note.

just an idea.
