### ISSUE TITLE
[Feature Request] Support for Sostenuto Pedal (CC 66)

### ISSUE THREAD

**Issue by chipweinberger** [sinshu/meltysynth#57]
I have users asking for Sostenuto support.

Curious to see how you would implement it.

**Comment by sinshu** [comment]
I just learned about the Sostenuto feature for the first time. As I understand it, Sostenuto applies the same effect as the hold pedal but only to the notes that are being played at the moment it is turned ON. If I were to implement it, I would do so as shown in the following fork. Note that this code has not been tested at all:
https://github.com/sinshu/meltysynth/tree/cc66

**Comment by chipweinberger** [comment]
> Sostenuto applies the same effect as the hold pedal but only to the notes that are being played at the moment it is turned ON. 

Yes exactly.

Thanks for the commits!! Super helpful!

**Comment by chipweinberger** [comment]
I added support here: https://github.com/chipweinberger/dart_melty_soundfont/commit/a94ebb9694b83a03b66c0ab20230842adc2471b0

and it works!

Thanks.

Are you going to implement it too? Should I leave it open?

**Comment by sinshu** [comment]
I'm glad the code worked fine 😁

Since this feature is unlikely to be used much for purposes like game BGM, I've decided not to implement it in MeltySynth for now.
